import React, { useState } from 'react';
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import styles from  "../../styles/gallery.module.css"
import Image from "next/image";
import Head from "next/head";
const Banner = () => {
    const settings = {
        dots: true,
        infinite: true,
        speed: 500,
        slidesToShow: 1,
        slidesToScroll: 1,

    };

    const [images, setImage] = useState([
        {id:1, image:'https://www.poel.am/_next/image?url=https%3A%2F%2Fpoels.geeklab.am%2Fuploads%2F1713215713_image.jpg&w=1200&q=75'},
        {id:2, image: 'https://www.poel.am/_next/image?url=https%3A%2F%2Fpoels.geeklab.am%2Fuploads%2F1713215998_image.jpg&w=1200&q=75'},
        {id:3, image: 'https://www.poel.am/_next/image?url=https%3A%2F%2Fpoels.geeklab.am%2Fuploads%2F1713216117_image.jpg&w=1200&q=75'},
        {id:4, image:'https://www.poel.am/_next/image?url=https%3A%2F%2Fpoels.geeklab.am%2Fuploads%2F1713216221_image.jpg&w=1200&q=75'},
        {id:5,image:'https://www.poel.am/_next/image?url=https%3A%2F%2Fpoels.geeklab.am%2Fuploads%2F1713216421_image.jpg&w=1200&q=75'},
    ]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.gallery}>
                <Slider {...settings}>
                    {images.map((element) => (
                        <div key={element.id} className={styles.slide}>
                            <Image width={800} height={800} src={element.image} alt="chi bana" />
                        </div>
                    ))}
                </Slider>
            </div>
        </>
    );
};

export default Banner;
