import Head from "next/head"; // Correct import for Head component
import { Inter } from "next/font/google"; // Correct import for font
import Index from "@/pages/home";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1"/> {/* Fixed typo in viewport meta tag */}
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Index/>
            </main>
        </>
    );
}
